# Generated by Django 5.0.6 on 2024-07-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalisation', '0002_alter_location_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='modèle',
            new_name='modele',
        ),
    ]
