# Generated by Django 5.0.6 on 2024-07-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalisation', '0003_rename_modèle_voiture_modele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='devise',
            field=models.CharField(choices=[('USD', 'Dollar américain'), ('CDF', 'Franc congolais'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
    ]
