# Generated by Django 5.0.6 on 2024-07-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalisation', '0004_alter_commander_devise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_prise', models.DateTimeField()),
                ('etat', models.CharField(max_length=100)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalisation.chauffeur')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalisation.voiture')),
            ],
        ),
    ]
